version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/expression-language
    versions:
    - 4.4.18
  - dependency-name: symfony/twig-bundle
    versions:
    - 4.4.16
  - dependency-name: symfony/validator
    versions:
    - 4.4.16
  - dependency-name: symfony/browser-kit
    versions:
    - 4.4.14
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.1.1
